apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t93ep3osp-nodejs
  janus-idp.io/tekton: t93ep3osp-nodejs
  backstage.io/kubernetes-id: t93ep3osp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t93ep3osp-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
