apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t93ep3osp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t93ep3osp-nodejs 
  name: t93ep3osp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: t93ep3osp-nodejs 
